import { useState, useCallback } from "react";
import {
  Sparkle,
  Copy,
  Check,
  CircleNotch,
  ArrowCounterClockwise,
  Warning,
} from "@phosphor-icons/react";
import { MermaidRenderer } from "../../../components/ui/MermaidRenderer";
import { useTabsStore } from "../../../stores/tabs-store";
import { usePanelFontSize, useUIStore } from "../../../stores/ui-store";
import { generateDiagram } from "../../../lib/tauri";

export function AIDiagramView() {
  const { repository } = useTabsStore();
  const { cliStatus } = useUIStore();
  const panelFontSize = usePanelFontSize();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [diagramSource, setDiagramSource] = useState<string>("");
  const [copied, setCopied] = useState(false);

  const claudeAvailable = cliStatus?.claude.available ?? true;

  const handleGenerate = useCallback(async () => {
    if (!repository?.path || isLoading) return;

    setIsLoading(true);
    setError(null);

    try {
      const diagram = await generateDiagram(repository.path);
      setDiagramSource(diagram);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to generate diagram";
      setError(message);
      setDiagramSource("");
    } finally {
      setIsLoading(false);
    }
  }, [repository?.path, isLoading]);

  const handleCopy = useCallback(async () => {
    if (!diagramSource) return;
    try {
      await navigator.clipboard.writeText(diagramSource);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, [diagramSource]);

  if (!repository) {
    return (
      <div className="flex items-center justify-center h-full text-text-muted">
        <p style={{ fontSize: `${panelFontSize}px` }}>No repository selected</p>
      </div>
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-text-muted gap-3 p-4">
        <CircleNotch size={32} className="animate-spin text-accent-purple" />
        <p style={{ fontSize: `${panelFontSize}px` }} className="text-text-primary font-medium">
          Generating diagram...
        </p>
        <p className="text-xs text-text-muted">
          Claude is analyzing your changes
        </p>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-text-muted gap-4 p-4">
        <Warning size={48} weight="duotone" className="text-accent-red" />
        <div className="text-center">
          <p style={{ fontSize: `${panelFontSize}px` }} className="text-text-primary font-medium mb-2">
            Failed to generate diagram
          </p>
          <p className="text-xs text-text-muted max-w-xs">
            {error}
          </p>
        </div>
        <button
          onClick={handleGenerate}
          className="flex items-center gap-2 px-4 py-2 bg-accent-purple text-white rounded-lg text-sm font-medium hover:bg-accent-purple/90 transition-colors"
        >
          <ArrowCounterClockwise size={16} weight="bold" />
          Try Again
        </button>
      </div>
    );
  }

  // Has diagram - show it
  if (diagramSource) {
    return (
      <div className="flex flex-col h-full">
        {/* Toolbar */}
        <div className="flex items-center justify-between px-3 py-2 border-b border-border-primary bg-bg-tertiary">
          <div className="flex items-center gap-2">
            <Sparkle size={14} className="text-accent-purple" />
            <span className="text-xs text-text-muted">Generated by Claude</span>
          </div>
          <div className="flex items-center gap-1">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-2 py-1 text-xs text-text-muted hover:text-text-primary hover:bg-bg-hover rounded-sm transition-colors"
            >
              {copied ? (
                <>
                  <Check size={12} weight="bold" className="text-accent-green" />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={12} />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={handleGenerate}
              className="flex items-center gap-1.5 px-2 py-1 text-xs text-text-muted hover:text-text-primary hover:bg-bg-hover rounded-sm transition-colors"
              title="Regenerate"
            >
              <ArrowCounterClockwise size={14} weight="bold" />
            </button>
          </div>
        </div>

        {/* Diagram */}
        <div className="flex-1 overflow-hidden p-4 min-h-0">
          <MermaidRenderer source={diagramSource} className="w-full h-full" />
        </div>
      </div>
    );
  }

  // Empty state - prompt to generate
  return (
    <div className="flex flex-col items-center justify-center h-full text-text-muted gap-4 p-6">
      <Sparkle size={48} weight="duotone" className="text-accent-purple" />
      <div className="text-center">
        <h3 className="text-lg font-medium text-text-primary mb-2">
          AI Sequence Diagram
        </h3>
        <p className="text-sm text-text-muted max-w-xs mb-1">
          Claude will analyze your changes and generate a sequence diagram showing how components interact.
        </p>
      </div>

      {!claudeAvailable && (
        <div className="w-full max-w-sm p-3 bg-accent-yellow/10 border border-accent-yellow/30 rounded-lg">
          <div className="flex items-start gap-2">
            <Warning size={16} weight="fill" className="text-accent-yellow shrink-0 mt-0.5" />
            <div className="text-left">
              <p className="text-sm font-medium text-text-primary">Claude CLI not installed</p>
              <p className="text-xs text-text-muted mt-1">
                {cliStatus?.claude.installInstructions}
              </p>
            </div>
          </div>
        </div>
      )}

      <button
        onClick={handleGenerate}
        disabled={!claudeAvailable}
        className="flex items-center gap-2 px-4 py-2 bg-accent-purple text-white rounded-lg text-sm font-medium hover:bg-accent-purple/90 disabled:bg-bg-tertiary disabled:text-text-muted disabled:cursor-not-allowed transition-colors"
      >
        <Sparkle size={16} weight="bold" />
        Generate Diagram
      </button>
    </div>
  );
}

export default AIDiagramView;
